# Generated by Django 4.2.23 on 2025-06-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_dob_customuser_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
