# Generated by Django 4.2.23 on 2025-06-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_current_employee',
            field=models.BooleanField(default=True),
        ),
    ]
