# Generated by Django 4.2.23 on 2025-06-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_profile_picture'),
        ('users', '0008_attendance'),
    ]

    operations = [
    ]
