# Generated by Django 4.2.23 on 2025-06-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_0007_customuser_profile_picture_0008_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
