# Generated by Django 4.2.23 on 2025-06-19 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=20)),
                ('login_time', models.TimeField()),
                ('logout_time', models.TimeField(blank=True, null=True)),
                ('eod_report', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='attendance_docs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
