# Generated by Django 4.2.23 on 2025-06-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
